"""
Django settings for sistema-gestao project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: keep the secret key used in production secret!
# Em produção, defina a variável de ambiente SECRET_KEY na plataforma de deploy.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-ph55lm4$my&jl&$cz$aeq(tsl-%f5zwwajb!ka4%u63mvv&6nv',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', False)

# Em produção, defina ALLOWED_HOSTS via variável de ambiente (hosts separados por vírgula).
# Ex.: ALLOWED_HOSTS=meusite.com,www.meusite.com
ALLOWED_HOSTS = ['gest-io.onrender.com']


# Application definition
# Sem django.contrib.admin/auth/contenttypes/sessions: nenhum app usa banco de
# dados, login ou o painel admin — os produtos persistem dados no localStorage
# do navegador.

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'apps.core',
    'apps.cronograma',
    'apps.temporizador',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Destino do `collectstatic` em produção — servido pelo WhiteNoise.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Segurança
# O cookie de CSRF só é enviado por HTTPS em produção. Redirecionamento HTTPS
# (SECURE_SSL_REDIRECT) e HSTS dependem de como a plataforma de deploy termina
# o TLS (proxy reverso) — configure-os quando a plataforma for definida, para
# não confiar cegamente em cabeçalhos como X-Forwarded-Proto sem essa garantia.
CSRF_COOKIE_SECURE = not DEBUG
